// Loads persona.json (generated by tools/persona_builder.py) and turns it
// into the system prompt. This is the "control the AI's behavior" layer:
// edit persona.json — or rerun the Python builder — to change how the
// assistant talks, without touching any JS.

const DEFAULT_PERSONA = {
  ai_name: "Afroica AI",
  user_name: "",
  tone: "warm, clear, and concise",
  expertise: [
    "African languages",
    "African cultures and history",
    "everyday practical topics"
  ],
  instructions: ""
};

export async function loadPersona(){
  try{
    const res = await fetch('persona.json', { cache: 'no-store' });
    if(!res.ok) throw new Error('persona.json not found (' + res.status + ')');
    const data = await res.json();
    return { ...DEFAULT_PERSONA, ...data };
  }catch(err){
    console.warn('Using default persona — could not load persona.json:', err.message);
    return DEFAULT_PERSONA;
  }
}

// Only ever used for the on-device WebLLM fallback (Pro sends this to the
// backend instead, which builds its own — see backend/app/llm.py — and
// includes the image-capability line there since Claude actually is
// vision-capable, unlike the text-only local model this feeds).
export function buildSystemPrompt(persona){
  const parts = [`You are ${persona.ai_name}, a helpful assistant.`];

  if(persona.expertise && persona.expertise.length){
    parts.push(`You have strong knowledge of: ${persona.expertise.join(', ')}.`);
  }
  if(persona.user_name){
    parts.push(`You're talking with ${persona.user_name} — address them by name when it feels natural.`);
  }
  if(persona.tone){
    parts.push(`Tone: ${persona.tone}.`);
  }
  parts.push(
    "Answer the user's actual question directly and specifically first — " +
    "don't open with generic background, disclaimers, or unrelated context " +
    "unless it's needed to answer. Stay on the topic they actually asked about."
  );
  if(persona.instructions){
    parts.push(persona.instructions);
  }

  return parts.join(' ');
}
